# Generated by Django 2.2.3 on 2019-07-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentMarks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastName',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
