# Generated by Django 2.2.3 on 2019-07-25 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentMarks', '0002_auto_20190725_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='emailAddress',
        ),
    ]
