# Generated by Django 2.2.3 on 2019-07-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentMarks', '0004_auto_20190725_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
